version: '3.8'

services:
  # Banco de Dados para armazenar os históricos
  db:
    image: postgres:15-alpine
    container_name: gemini_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_123
      POSTGRES_DB: mini_gemini_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Motor das LLMs
  ollama:
    image: ollama/ollama
    container_name: gemini_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama

  # Seu App (Front + Backend)
  app:
    build: ./app
    container_name: gemini_app
    restart: always
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://user_admin:password_123@db:5432/mini_gemini_db
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - db
      - ollama

volumes:
  postgres_data:
  ollama_storage: